apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devtrackr-ingress
  namespace: devtrackr
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: devtrackr.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: api.devtrackr.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
